package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

public class InicioSesionController {
	@FXML
	private TextField txtNombre;
	@FXML
	private PasswordField txtContrasena;
	@FXML
	private Button btnEntrar;
	@FXML
	private Label lblMensaje;

	// Event Listener on Button[#btnEntrar].onAction
	@FXML
	public void mostrrMensaje(ActionEvent event) {
		// TODO Autogenerated
		lblMensaje.setText("Bienvenid@ "+ txtNombre.getText());
		txtNombre.setText("");
		txtContrasena.setText("");
	}
}
